language: ruby
cache:
  directories:
  - vendor/bundle
sudo: false
rvm:
  - '1.9'
  - '2.1.8'
  - '2.2.4'
  - '2.3.0'
  - 'ruby-head'
  - 'jruby'

install: bundle install --jobs=3 --retry=3

script: bundle exec rake spec

after_success:
  coveralls
